# =====================================================================
#                      GUÍA DE USO DEL DOCKER-COMPOSE
# =====================================================================
#
# IMPORTANTE:
#
# 1. ARCHIVO .ENV - No es necesario modificarlo. Las variables de entorno
#    para los contenedores se definen en "x-app-environment: &app-environment"
#
# 2. CERTIFICADOS DE SEGURIDAD:
#    - Deben colocarse en la carpeta "scripts/temp" del proyecto
#    - Si la carpeta no existe, créala
#    - El nombre del certificado debe ser el NIT del contribuyente
#
# 3. MODIFICACIONES:
#    - No modifiques este archivo a menos que sea estrictamente necesario
#    - Si agregas nuevos servicios, verifica su correcta configuración
#
# 4. PRECAUCIÓN:
#    - Cualquier cambio debe ser justificado y entendido previamente
#
# =====================================================================

# Variables globales reutilizables
x-app-environment: &app-environment
  # Configuración de la aplicación
  APP_NAME: DTE-Microservice

  APP_LANG: en # Actualmente soporta es y en
  DEBUG: true
  FORCE_CONTINGENCY: false # Forzar el uso de contingencia
  RUN_MIGRATION: false

  SERVER_PORT: 7319
  ADMIN_EMAIL: example@example.com
  MH_AMBIENT_CODE: "00"
  MH_MAX_BATCH_SIZE: 100
  JWT_SECRET: TU-SECRET # Cambiar por tu cadena secreta

  LOG_LEVEL: debug
  LOG_PATH: /pkg/shared/logs/
  LOG_FILE_LOGGING: true

  # Configuración de bases de datos
  DB_DRIVER: mysql #mysql o postgres
  DB_HOST: mysql #No modificar
  DB_PORT: 3306 #No modificar
  DB_DATABASE: dte_db
  DB_USERNAME: root
  DB_PASSWORD: root_password
  DB_CHARSET: utf8mb4

  # Configuración de Redis
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASSWORD:

  # Configuración del firmador
  SIGNER_PATH: http://signer:8113/firmardocumento/
  SIGNER_HEALTH: http://signer:8113/firmardocumento/status

  # Configuración de servicios de Hacienda
  MH_AUTH_URL: https://apitest.dtes.mh.gob.sv/seguridad/auth
  MH_RECEPTION_URL: https://apitest.dtes.mh.gob.sv/fesv/recepciondte
  MH_LOTE_RECEPTION_URL: https://apitest.dtes.mh.gob.sv/fesv/recepcionlote/
  MH_RECEPTION_CONSULT_URL: https://apitest.dtes.mh.gob.sv/fesv/recepcion/consultadte/
  MH_RECEPTION_CONSULT_LOTE_URL: https://apitest.dtes.mh.gob.sv/fesv/recepcion/consultadtelote
  MH_CONTINGENCY_URL: https://apitest.dtes.mh.gob.sv/fesv/contingencia
  MH_NULLIFY_URL: https://apitest.dtes.mh.gob.sv/fesv/anulardte

x-mysql-environment: &mysql-environment
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: dte_db
  MYSQL_USER: dte_user
  MYSQL_PASSWORD: app_password

services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      <<: *mysql-environment
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
      - dte_network

  # Servicio de Redis
  redis:
    image: redis:7.4.2
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server
    networks:
      - dte_network

  # Servicio de Firmador de Hacienda
  signer:
    image: svfe/svfe-api-firmador:v20230109
    container_name: signer-container
    ports:
      - "8113:8113"
    volumes:
      - "./temp:/uploads"
    networks:
      - dte_network

  # Servicio para producción
  backend:
    image: golang:1.23-alpine
    container_name: dte-container
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "7319:7319"
    command: sh -c "go run ./cmd/main.go"
    depends_on:
      - mysql
      - redis
    environment:
      <<: *app-environment
    networks:
      - dte_network
    profiles:
      - dev2

  # Servicio para desarrollo (Hot Reload)
  backend-dev:
    image: golang:1.23-alpine
    container_name: dte-container-dev
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "7319:7319"
    command: sh -c "go mod download && go run ./cmd/main.go"
    depends_on:
      - mysql
      - redis
    environment:
      <<: *app-environment
    networks:
      - dte_network
    profiles:
      - dev

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  dte_network:
    driver: bridge